#!/usr/bin/env perl
use v5.14;
use HTTP::Tiny;
use JSON::PP;

# fetch records via unAPI and print as newline delimted PICA/JSON

require './lib/Config.pm'; ## no critic

my $config = Config::load('config/config');
my $unapi = $config->{unapi}{url};
my $dbkey = $config->{unapi}{dbkey};
my $http = HTTP::Tiny->new;

for my $ppn (<>) {
    chomp $ppn;
    die "invalid PPN '$ppn' in line $.\n" unless $ppn =~ /^[0-9]+[0-9X]$/;
    my $url = "$unapi?format=picajson&id=$dbkey:ppn:$ppn";
    my $res = $http->get($url);
    die "failed unAPI request: $url" unless $res->{success};
    say encode_json(decode_json($res->{content}));
}
