#!/usr/bin/env perl
use v5.14;
use PICA::Data ':all';

# reduce pica records to subject indexing fields

require './lib/Config.pm'; ## no critic

my @schemes = grep { $_ } values %{ Config::load('config/schemes') };
my @fields = map { pica_path($_) } '003@', map { $_->{PICAPATH} } @schemes;
 
my $parser = pica_parser('JSON', $ARGV[0]);
my $writer = pica_writer('JSON');

while ( my $record = $parser->next ) {
    $writer->write( pica_fields($record, @fields) );
}
